version: '3.8'

services:
  pgvector:
    image: ankane/pgvector:latest # Or specify a specific version like pgvector/pgvector:pg16
    container_name: pgvector-demo
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=vectordb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgvector_init:/docker-entrypoint-initdb.d # Mount init scripts
      - pgvector_data:/var/lib/postgresql/data # Optional: for data persistence

  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: qdrant-demo
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  migration-tool:
    image: python:3.9-slim
    container_name: migration-demo
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install . requests && tail -f /dev/null" # requests might be needed by other scripts
    depends_on:
      - pgvector # Depends on the pgvector service key

  qwen3-processor:
    container_name: qwen3-processor-demo
    build:
      context: ./docker/qwen3_processor
      # dockerfile: Dockerfile # Default
    volumes:
      - .:/app # Mount current project directory to /app
    environment:
      - PGVECTOR_HOST=pgvector-demo
      - PGVECTOR_PORT=5432
      - PGVECTOR_USER=testuser
      - PGVECTOR_PASSWORD=testpassword
      - PGVECTOR_DB=vectordb
      - QDRANT_HOST=qdrant-demo
      - QDRANT_PORT=6333
      - HF_HUB_ENABLE_HF_TRANSFER=1 # For potentially faster Hugging Face downloads
    depends_on:
      - pgvector # Service key for pgvector
      - qdrant   # Service key for qdrant
    command: tail -f /dev/null # Placeholder, will be replaced by Dockerfile CMD or overridden

volumes: # Define named volumes for data persistence (optional but good practice)
  pgvector_data:
  qdrant_data:
